maxBountiesPerFaction = 5
announceChannel = {}
playChannel = {}
botLoggedIn = False
# can be fixed or random
newBountyDelayType = "fixed"
newBountyFixedDailyTime = {"hours":18, "minutes":40, "seconds":0}
newBountyFixedUseDailyTime = False
newBountyFixedDelta = {"days":0, "hours":2, "minutes":0, "seconds":0}
newBountyFixedDeltaChanged = False
newBountyDelayReset = False
newBountyDelayMin = 300
newBountyDelayMax = 4 * 60 * 60
saveDelay = 30 * 60
delayFactor = 5
bPointsToCreditsRatio = 100
randomDrinkFactor = 1000
randomDrinkNum = int(randomDrinkFactor / 3)
checkCooldown = {"minutes":3}