maxBountiesPerFaction = 5
botLoggedIn = False
# can be fixed or random
newBountyDelayType = "fixed"
newBountyFixedDailyTime = {"hours":18, "minutes":40, "seconds":0}
newBountyFixedUseDailyTime = False
newBountyFixedDelta = {"days":0, "hours":2, "minutes":0, "seconds":0}
newBountyFixedDeltaChanged = False
newBountyDelayReset = False
newBountyDelayMin = 300
newBountyDelayMax = 4 * 60 * 60
saveDelay = 30 * 60
delayFactor = 5
bPointsToCreditsRatio = 100
randomDrinkFactor = 500
randomDrinkNum = int(randomDrinkFactor / 3)
checkCooldown = {"minutes":3}
userDBPath = "saveData/users.json"
guildDBPath = "saveData/guilds.json"
bountyDBPath = "saveData/bounties.json"
commandPrefix = "!bb "
developers = [188618589102669826]
closeBountyThreshold = 4
devTitle = "officer"
adminTitle = "commander"
userTitle = "pilot"